config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :daily_logs
  get 'signup', to: 'users#new' 


  resources :users, except: [:new] 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  resources :individual_vitals_logs
  resources :individuals, except: [:destroy]  do 
    resources :individual_vitals_logs #only: [:new, :index, :show]
  end 

  

  resources :daily_activities, except: [:destroy]


end

app/models/individual.rb
class Individual < ApplicationRecord 
  validates :name, presence: true
  validates :bio, presence: true
 
has_many :daily_logs

has_many :individual_vitals_logs
 
end 

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
   before_action :require_admin, except: [:index, :show]
   
  def new
    @individual = Individual.new

  end 

  def create
     @individual = Individual.new(individual_params)
     if @individual.save
      redirect_to @individual

     else 
      render 'new'
     end 
  end 

  def index
    @individuals = Individual.all
  end 

  def show
    @individual = Individual.find(params[:id])
  end 

  private

  def individual_params
    params.require(:individual).permit(:name, :bio)
  end 

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only the manager of Our Home can perform this action"
      redirect_to individuals_path
    end 
  end 
  
end 

app/views/individuals/_individual.html.erb
<%= link_to individual.name, individual_path(individual) %>

app/views/individuals/index.html.erb
<div class="container">
<h1 class="text-center mt-4">Individuals</h1>
    <% @individuals.each do |individual| %>
      <div class="row justify-content-md-center">
        <div class="col-6 mt-4">
          <div class="card text-center mb-4 bg-white rounded">
            <div class="card-body">
              <h5 class="card-title">Name: <%= link_to individual.name, individual_path(individual) %></td></h5>
                <p class="card-text"><%= truncate(individual.bio, length: 100) %>
                </p>
                <%= link_to "View",  individual_path(individual), class: "btn btn-outline-dark" %>
            </div>   
          </div>
        </div>
      </div>
    <% end %> 
  </div> 

app/views/individuals/new.html.erb
<h1 class="text-center mt-4">Enter a new Individual</h1>

<div class="container">
<%= form_with(model: @individual, class: "shadow p-3 mb-3 bg-light rounded", local: true ) do |f| %>
  <div class="form-group row">
  <p>
    <%= f.label :Name , class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a new individual"  %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :Bio, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= f.text_area :bio, rows: 10, class: "form-control shadow rounded", placeholder: "Enter Individual's Biography"  %>
    </div>
  </div>

            <div class="form-group row">
            <%= f.submit class: "btn btn-outline-light btn-primary" %>
            </div>
  

<% end %>
</div>

</div>
</div>

app/views/individuals/show.html.erb
<h2 class="text-center mt-4"><%= @individual.name %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center  mb-4 bg-white rounded">
          <div class="card-body">
            <div class="card-text text-center"><%= simple_format(@individual.bio) %></div>
            <% if logged_in? %>
              <%= link_to "Enter Vitals",  new_individual_individual_vitals_log_path(@individual), class: "btn btn-primary" %>
            <% end %> 
          <div>
        </div>    
      </div> 
    </div>   
  </div>         