config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :daily_logs
  get 'signup', to: 'users#new' 


  resources :users, except: [:new] 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  resources :individual_vitals_logs
  resources :individuals, except: [:destroy]  do 
    resources :individual_vitals_logs #only: [:new, :index, :show]
  end 

  

  resources :daily_activities, except: [:destroy]


end

app/models/daily_log.rb
class DailyLog < ApplicationRecord 
  belongs_to :user
  belongs_to :individual
  


  validates :shift, presence: true
  validates :notes, presence: true, length: {minimum: 10, maximum: 400}
end 

app/controllers/daily_logs_controller.rb
class DailyLogsController < ApplicationController
  before_action :set_daily_log, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

def show
  #calls the private method
end 

def index
  @daily_logs = DailyLog.all
end 

def new
  @daily_log = DailyLog.new
end 

def edit
  #calls the private method
end 

def create
  @daily_log = DailyLog.new(daily_log_params) #calls the private method
  @daily_log.user = current_user

  if  @daily_log.save 
    flash[:notice] = "notes were created successfully."
  redirect_to daily_log_path(@daily_log) #extracts daily_log's id 
  else
    render 'new'
  end 
end 

def update

  if @daily_log.update(daily_log_params) #calls a private method
    flash[:notice] = "The Daily Log was updated succesfully"
    redirect_to daily_log_path(@daily_log)
  else 
    render 'edit'
  end 
end 

def destroy
   #calls the private method (set_daily_log)
  @daily_log.destroy
  redirect_to daily_logs_path
end 

private

def set_daily_log
  @daily_log = DailyLog.find(params[:id])
end 

def daily_log_params
  params.require(:daily_log).permit(:shift, :notes, :individual_id)
end 

def require_same_user
  if current_user != @daily_log.user && !current_user.admin? 
    flash[:alert] = "You can only edit or delete you own notes."
    redirect_to @daily_log
  end 
end 

end 

app/views/daily_logs/_daily_log.html.erb
<div class="container">
  <% @daily_logs.each do |log| %>
    <div class="row justify-content-md-center">
    <div class="col-6 mt-4">
    <div class="card text-center  mb-4 bg-white rounded">

    <% if log.user %>
    by <%= link_to log.user.username, user_path(log.user) %>
  <% end %>
            <div class="card-body">
            <h5 class="card-title">Shift: <%= link_to log.shift, daily_log_path(log) %></td><h5>
                <p class="card-text"><%= truncate(log.notes, length: 100) %>
                </p> 
                <%= link_to "View",  daily_log_path(log), class: "btn btn-outline-dark" %>

                <% if logged_in? && (log.user == current_user || current_user.admin?) %>

                <%= link_to "Edit", edit_daily_log_path(log), class: "btn btn-outline-dark" %>
      
                <%= link_to "Delete", daily_log_path(log), class: "btn btn-outline-light btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                <% end %>
                </div>
                   
             
                     <div class="card-footer text-muted">
                       <small>Entered Logs <%= log.created_at %></small>
                    </div>
                     
     
                  
       </div>
       </div>
      </div>                   
  <% end %> 
  </div>
  

app/views/daily_logs/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @daily_log %>
      <%= form_for @daily_log do |f| %>
        <div class="form-group row">
          <%= f.label :shift, class: "col-2 col-form-label" %>
          
          <div class="col-10">
            <%= f.text_field :shift, class: "form-control ", placeholder: "Shift:" %>
          </div>
        </div>   

        <div class="form-group row">
          <%= f.label :Individual, class: "col-2 col-form-label" %>
            <div class="col-10">   
              <%= f.select :individual_id, Individual.all.map {|i| [i.name, i.id]} %>
            </div>
        </div> 

          

        <div class="form-group row">
          <%= f.label :notes, class: "col-2 col-form-label" %>
            <div class="col-10"> 
            <%= f.text_area :notes, rows: 10, class: "form-control shadow rounded", placeholder: "Notes:" %>
            </div>
        </div>  
          
          
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-dark btn-lg" %>
        </div>  
      <% end %>
      </div>
   

      <div class="mb-3">
        <%= link_to '[ Return to Daily Logs listing ]', daily_logs_path %>
      </div>
  </div>
</div>    
  
 

   
  

app/views/daily_logs/edit.html.erb
<h1 >Edit Daily Log</h1>
<%= render 'form' %>

app/views/daily_logs/index.html.erb
<h1 class="text-center mt-4">Listing all Daily Logs</h1>

<%= render 'daily_log' %>



   
   
 

    

app/views/daily_logs/new.html.erb
<h1 class="text-center mt-4">Create new Daily Log</h1>
<%= render 'form' %>

  

app/views/daily_logs/show.html.erb
<h2 class="text-center mt-4"><%= @daily_log.shift %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center  mb-4 bg-white rounded">
         

            by <%= @daily_log.user.username if @daily_log.user %>
            

                      
            <div class="mt-2"><%= render @daily_log.individual %></div>
        
          
                
            <div class="card-body">
              <div class="card-text text-left"><%= simple_format(@daily_log.notes) %></div>
              <% if logged_in? && (@daily_log.user == current_user || current_user.admin?) %>

              <%= link_to "Edit", edit_daily_log_path(@daily_log), class: "btn btn-outline-dark" %>

              <%= link_to "Delete", daily_log_path(@daily_log), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </div>

            <div class="card-footer text-muted">
              <small>Entered <%= time_ago_in_words(@daily_log.created_at) %> ago</small>
            </div>
        </div>
      </div>
    </div>
  </div>
            
        
        