config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :daily_logs
  get 'signup', to: 'users#new' 


  resources :users, except: [:new] 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  resources :individual_vitals_logs
  resources :individuals, except: [:destroy]  do 
    resources :individual_vitals_logs #only: [:new, :index, :show]
  end 

  

  resources :daily_activities, except: [:destroy]


end

app/models/daily_activity.rb
class DailyActivity < ApplicationRecord 
  validates :title, presence: true

  

end 

app/controllers/daily_activities_controller.rb
class DailyActivitiesController < ApplicationController

  def new
    @daily_activity = DailyActivity.new
  end 

  def create
    @daily_activity = DailyActivity.new(daily_activity_params)
    if @daily_activity.save
      flash[:notice] = "Activity was successfully created"
      redirect_to @daily_activity

    else 
      render 'new'
    end 
  end 

  def index
    @daily_activities = DailyActivity.all
  end 

  def show
    @daily_activity = DailyActivity.find(params[:id])
  end 

  private

  def daily_activity_params
    params.require(:daily_activity).permit(:title, :description)

  end 

  
  
end 

app/views/daily_activities/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
      <div class="col-10">
      <%= form_with(model: @daily_activity, local: true ) do |f| %>
          <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %>
              <div class="col-10">
              <%= f.text_field :title,  placeholder: "enter a title"  %>
              </div>
          </div>    
      
          <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %>
              <div class="col-10">
              <%= f.text_area :description, rows: 10,class: "form-control shadow rounded", placeholder: "write a description"  %>
              </div>
          </div>    
        

          <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-dark btn-lg" %>
          </div>
      <% end %>
      </div>
  </div>
</div>        

app/views/daily_activities/index.html.erb
<div class="container">
   <h1 class="text-center mt-4"> All Daily Activities</h1>
      <% @daily_activities.each do |activity| %>
         <div class="row justify-content-md-center">
            <div class="col-6 mt-4">
               <div class="card text-center mb-4 bg-white rounded">
                  <div class="card-body">
                     <h5 class="card-title">Daily Activity: <%= link_to activity.title, daily_activity_path(activity) %></td></h5>
                     <p><%= truncate(activity.description, length: 100) %>
                     </p>
                     <%= link_to "View",  daily_activity_path(activity), class: "btn btn-outline-dark" %>
                  </div>
               </div>
            </div>   
         </div>  
      <% end %> 
<div>
 

app/views/daily_activities/new.html.erb
<h1 class="text-center mt-4">Create a new Daily Activity</h1>
<%= render 'form' %>

   

app/views/daily_activities/show.html.erb
<h2 class="text-center mt-4"><%= @daily_activity.title %></p></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center  mb-4 bg-white rounded">

          <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@daily_activity.description) %></div>
          </div>      
        </div>
      <div>
    </div>    
  </div>          
          