config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :daily_logs
  get 'signup', to: 'users#new' 


  resources :users, except: [:new] 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  resources :individual_vitals_logs
  resources :individuals, except: [:destroy]  do 
    resources :individual_vitals_logs #only: [:new, :index, :show]
  end 

  

  resources :daily_activities, except: [:destroy]


end

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "OUR HOME", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
         
          <li class="nav-item">
            
          <%= link_to "Staff", users_path, class: "nav-link" %>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Daily Logs
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <% if logged_in? %>
              
              <%= link_to "Add Notes", new_daily_log_path, class: "dropdown-item" %>
            <% end %>

              <%= link_to "View Daily Logs", daily_logs_path, class: "dropdown-item" %>
             
          </li>

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Individuals
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? && current_user.admin?  %>
            <%= link_to "Add a new Individual", new_individual_path, class: "dropdown-item" %>
          <% end %>

          <% if logged_in? %>
              <%= link_to "View Vitals", individual_vitals_logs_path, class: "dropdown-item" %>
          <% end %> 

            <%= link_to "View Individuals", individuals_path, class: "dropdown-item" %>


        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Daily Activities
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            
            <%= link_to "Create an activity", new_daily_activity_path, class: "dropdown-item" %>
          <% end %>

            <%= link_to "View all activities", daily_activities_path, class: "dropdown-item" %>
         
          <% if logged_in? %>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

               <%= "Admin" if current_user.admin? %> Profile  <%    current_user.username %>
            </a>

              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           
              
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>

            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"} %>


            </div>
        </li>

            <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to 'Log In', login_path, class: "nav-link" %>
            </li>

            
            <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
            </li>

          <% end %>

        </ul>

       
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nursing Hom Logs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" >
  <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    
  </body>
</html>